import PDFDocument from "pdfkit";
import { formatPrice } from "@/lib/utils";

export function generateInvoiceNumber(prefix = "INV") {
  const now = new Date();
  const y = now.getFullYear();
  const m = String(now.getMonth() + 1).padStart(2, "0");
  const rand = Math.floor(1000 + Math.random() * 9000);
  return `${prefix}-${y}${m}-${rand}`;
}

export async function generateInvoicePdfBuffer(data: {
  invoiceNumber: string;
  issuedAt: Date;
  gymName: string;
  gstNumber?: string | null;
  amount: number;
}) {
  const doc = new PDFDocument({ size: "A4", margin: 50 });
  const chunks: Buffer[] = [];

  doc.on("data", (chunk) => chunks.push(chunk));

  doc.fontSize(20).text("FITDEX Invoice", { align: "left" });
  doc.moveDown();

  doc.fontSize(12).text(`Invoice No: ${data.invoiceNumber}`);
  doc.text(`Date: ${data.issuedAt.toLocaleDateString()}`);
  doc.moveDown();

  doc.fontSize(12).text(`Gym: ${data.gymName}`);
  if (data.gstNumber) {
    doc.text(`GST: ${data.gstNumber}`);
  }
  doc.moveDown();

  doc.fontSize(14).text(`Amount: ${formatPrice(data.amount)}`);

  doc.moveDown(2);
  doc.fontSize(10).fillColor("gray").text("Estimated tax invoices are generated by FITDEX.");

  doc.end();

  return await new Promise<Buffer>((resolve) => {
    doc.on("end", () => resolve(Buffer.concat(chunks)));
  });
}

type InvoiceItemLine = {
  description: string;
  quantity: number;
  unitPrice: number;
  total: number;
};

type InvoiceTaxLine = {
  label: string;
  rate: number;
  amount: number;
};

export async function generateOwnerInvoicePdfBuffer(data: {
  invoiceNumber: string;
  issuedAt: Date;
  gymName: string;
  gymAddress?: string | null;
  gymGstNumber?: string | null;
  memberName?: string | null;
  memberEmail?: string | null;
  items: InvoiceItemLine[];
  taxes: InvoiceTaxLine[];
  subtotal: number;
  taxTotal: number;
  total: number;
  layout?: "A4" | "THERMAL";
}) {
  const layout = data.layout ?? "A4";
  const pageSize = layout === "THERMAL" ? [226, 800] : "A4";
  const margin = layout === "THERMAL" ? 16 : 50;
  const doc = new PDFDocument({ size: pageSize, margin });
  const chunks: Buffer[] = [];

  doc.on("data", (chunk) => chunks.push(chunk));

  const titleSize = layout === "THERMAL" ? 14 : 20;
  const labelSize = layout === "THERMAL" ? 9 : 11;
  const bodySize = layout === "THERMAL" ? 10 : 12;

  doc.fontSize(titleSize).text("FITDEX Invoice", { align: "left" });
  doc.moveDown(0.5);

  doc.fontSize(labelSize).fillColor("#AEB8C4").text("Invoice No", { continued: true }).fillColor("#FFFFFF").text(` ${data.invoiceNumber}`);
  doc.fontSize(labelSize).fillColor("#AEB8C4").text("Date", { continued: true }).fillColor("#FFFFFF").text(` ${data.issuedAt.toLocaleDateString()}`);
  doc.moveDown(0.6);

  doc.fontSize(bodySize).fillColor("#FFFFFF").text(data.gymName);
  if (data.gymAddress) {
    doc.fontSize(labelSize).fillColor("#AEB8C4").text(data.gymAddress);
  }
  if (data.gymGstNumber) {
    doc.fontSize(labelSize).fillColor("#AEB8C4").text(`GSTIN: ${data.gymGstNumber}`);
  }
  doc.moveDown(0.6);

  if (data.memberName || data.memberEmail) {
    doc.fontSize(labelSize).fillColor("#AEB8C4").text("Billed to");
    if (data.memberName) {
      doc.fontSize(bodySize).fillColor("#FFFFFF").text(data.memberName);
    }
    if (data.memberEmail) {
      doc.fontSize(labelSize).fillColor("#AEB8C4").text(data.memberEmail);
    }
    doc.moveDown(0.6);
  }

  doc.fontSize(labelSize).fillColor("#AEB8C4").text("Items", { underline: true });
  doc.moveDown(0.3);

  data.items.forEach((item) => {
    doc.fontSize(bodySize).fillColor("#FFFFFF").text(item.description);
    doc.fontSize(labelSize)
      .fillColor("#AEB8C4")
      .text(`Qty ${item.quantity} × ${formatPrice(item.unitPrice)}  =  ${formatPrice(item.total)}`);
    doc.moveDown(0.2);
  });

  doc.moveDown(0.4);
  doc.fontSize(labelSize).fillColor("#AEB8C4").text("Subtotal", { continued: true, align: "left" }).fillColor("#FFFFFF").text(` ${formatPrice(data.subtotal)}`);

  if (data.taxes.length > 0) {
    data.taxes.forEach((tax) => {
      doc.fontSize(labelSize)
        .fillColor("#AEB8C4")
        .text(`${tax.label} (${tax.rate}%)`, { continued: true })
        .fillColor("#FFFFFF")
        .text(` ${formatPrice(tax.amount)}`);
    });
  }

  doc.fontSize(bodySize)
    .fillColor("#FFFFFF")
    .text(`Total  ${formatPrice(data.total)}`);

  doc.moveDown(layout === "THERMAL" ? 0.6 : 1.5);
  doc.fontSize(labelSize).fillColor("#AEB8C4").text("This invoice is generated by Fitdex for record keeping.");

  doc.end();

  return await new Promise<Buffer>((resolve) => {
    doc.on("end", () => resolve(Buffer.concat(chunks)));
  });
}
