import PDFDocument from "pdfkit";
import { formatPrice } from "@/lib/utils";

export function generateInvoiceNumber(prefix = "INV") {
  const now = new Date();
  const y = now.getFullYear();
  const m = String(now.getMonth() + 1).padStart(2, "0");
  const rand = Math.floor(1000 + Math.random() * 9000);
  return `${prefix}-${y}${m}-${rand}`;
}

export async function generateInvoicePdfBuffer(data: {
  invoiceNumber: string;
  issuedAt: Date;
  gymName: string;
  gstNumber?: string | null;
  amount: number;
}) {
  const doc = new PDFDocument({ size: "A4", margin: 50 });
  const chunks: Buffer[] = [];

  doc.on("data", (chunk) => chunks.push(chunk));

  doc.fontSize(20).text("FITDEX Invoice", { align: "left" });
  doc.moveDown();

  doc.fontSize(12).text(`Invoice No: ${data.invoiceNumber}`);
  doc.text(`Date: ${data.issuedAt.toLocaleDateString()}`);
  doc.moveDown();

  doc.fontSize(12).text(`Gym: ${data.gymName}`);
  if (data.gstNumber) {
    doc.text(`GST: ${data.gstNumber}`);
  }
  doc.moveDown();

  doc.fontSize(14).text(`Amount: ${formatPrice(data.amount)}`);

  doc.moveDown(2);
  doc.fontSize(10).fillColor("gray").text("Estimated tax invoices are generated by FITDEX.");

  doc.end();

  return await new Promise<Buffer>((resolve) => {
    doc.on("end", () => resolve(Buffer.concat(chunks)));
  });
}
